Page({
  data: {
    words: [
      {"phonetic":"/əˈbɪlɪti/","meaning":"the power or skill to do something","word":"ability"},
      {"phonetic":"/ˈeɪbəl/","meaning":"having the power, skill, or means to do something","word":"able"},
      {"phonetic":"/əˈbaʊt/","meaning":"on the subject of; roughly","word":"about"},
      {"phonetic":"/əˈbʌv/","meaning":"higher than; over","word":"above"},
      {"phonetic":"/əkˈsɛpt/","meaning":"to agree to take or receive","word":"accept"},
      {"phonetic":"/əˈkɔːrdɪŋ/","meaning":"as stated by or in","word":"according"},
      {"phonetic":"/əˈkaʊnt/","meaning":"a record or report of money or events","word":"account"},
      {"phonetic":"/əˈkrɔs/","meaning":"from one side to the other","word":"across"},
      {"phonetic":"/ækt/","meaning":"to do something; a law or performance","word":"act"},
      {"phonetic":"/ˈækʃən/","meaning":"the process of doing something","word":"action"},
      {"phonetic":"/ækˈtɪvɪti/","meaning":"something done for a purpose","word":"activity"},
      {"phonetic":"/ˈækʃuəli/","meaning":"in fact; really","word":"actually"},
      {"phonetic":"/æd/","meaning":"to put together or increase","word":"add"},
      {"phonetic":"/əˈdrɛs/","meaning":"details of where someone lives or speaks to someone","word":"address"},
      {"phonetic":"/ədˌmɪnɪˈstreɪʃən/","meaning":"management of operations or government","word":"administration"},
      {"phonetic":"/ədˈmɪt/","meaning":"to agree that something is true; to allow entry","word":"admit"},
      {"phonetic":"/ˈædʌlt/","meaning":"a fully grown person","word":"adult"},
      {"phonetic":"/əˈfɛkt/","meaning":"to influence","word":"affect"},
      {"phonetic":"/ˈæftər/","meaning":"later in time","word":"after"},
      {"phonetic":"/əˈɡɛn/","meaning":"one more time","word":"again"},
      {"phonetic":"/əˈɡɛnst/","meaning":"in opposition to","word":"against"},
      {"phonetic":"/eɪdʒ/","meaning":"how old someone or something is","word":"age"},
      {"phonetic":"/ˈeɪdʒənsi/","meaning":"an organization that provides a service","word":"agency"},
      {"phonetic":"/ˈeɪdʒənt/","meaning":"a person who acts for another","word":"agent"},
      {"phonetic":"/əˈɡoʊ/","meaning":"before now","word":"ago"},
      {"phonetic":"/əˈɡriː/","meaning":"to have the same opinion; to accept","word":"agree"},
      {"phonetic":"/əˈɡriːmənt/","meaning":"a decision or contract made between people","word":"agreement"},
      {"phonetic":"/əˈhɛd/","meaning":"in front; in the future","word":"ahead"},
      {"phonetic":"/ɛr/","meaning":"the mixture of gases we breathe","word":"air"},
      {"phonetic":"/ɔːl/","meaning":"every one; everything","word":"all"},
      {"phonetic":"/əˈlaʊ/","meaning":"to permit","word":"allow"},
      {"phonetic":"/ˈɔːlmoʊst/","meaning":"nearly","word":"almost"},
      {"phonetic":"/əˈloʊn/","meaning":"by oneself; without others","word":"alone"},
      {"phonetic":"/əˈlɔːŋ/","meaning":"moving in a line or beside","word":"along"},
      {"phonetic":"/ɔːlˈrɛdi/","meaning":"before now","word":"already"},
      {"phonetic":"/ˈɔːlsoʊ/","meaning":"in addition","word":"also"},
      {"phonetic":"/ɔːlˈðoʊ/","meaning":"in spite of the fact that","word":"although"},
      {"phonetic":"/ˈɔːlweɪz/","meaning":"at all times","word":"always"},
      {"phonetic":"/əˈmɛrɪkən/","meaning":"relating to the United States of America","word":"American"},
      {"phonetic":"/əˈmʌŋ/","meaning":"in the middle of, or with a group","word":"among"},
      {"phonetic":"/əˈmaʊnt/","meaning":"a quantity of something","word":"amount"},
      {"phonetic":"/əˈnæləsɪs/","meaning":"detailed examination of something","word":"analysis"},
      {"phonetic":"/ænd/","meaning":"used to connect words or phrases","word":"and"},
      {"phonetic":"/ˈænəməl/","meaning":"a living creature that is not a plant","word":"animal"},
      {"phonetic":"/əˈnʌðər/","meaning":"one more; an additional one","word":"another"},
      {"phonetic":"/ˈænsər/","meaning":"a response to a question","word":"answer"},
      {"phonetic":"/ˈɛni/","meaning":"one or some; no matter which","word":"any"},
      {"phonetic":"/ˈɛniˌwʌn/","meaning":"any person","word":"anyone"},
      {"phonetic":"/ˈɛniˌθɪŋ/","meaning":"any object, event, or matter","word":"anything"},
      {"phonetic":"/əˈpɪr/","meaning":"to become visible; to seem","word":"appear"},
      {"phonetic":"/əˈplaɪ/","meaning":"to make a formal request; to put on","word":"apply"},
      {"phonetic":"/əˈproʊtʃ/","meaning":"to come near; a way of doing something","word":"approach"},
      {"phonetic":"/ˈɛriə/","meaning":"a region or space","word":"area"},
      {"phonetic":"/ˈɑrɡjuː/","meaning":"to disagree or give reasons for","word":"argue"},
      {"phonetic":"/ɑrm/","meaning":"the limb from shoulder to hand; weapon","word":"arm"},
      {"phonetic":"/əˈraʊnd/","meaning":"surrounding; near","word":"around"},
      {"phonetic":"/əˈraɪv/","meaning":"to reach a place","word":"arrive"},
      {"phonetic":"/ɑrt/","meaning":"creative work like painting or music","word":"art"},
      {"phonetic":"/ˈɑrtɪkəl/","meaning":"a piece of writing in a newspaper or magazine","word":"article"},
      {"phonetic":"/ˈɑrtɪst/","meaning":"a person who creates art","word":"artist"},
      {"phonetic":"/æz/","meaning":"used for comparison or because","word":"as"},
      {"phonetic":"/æsk/","meaning":"to request information or action","word":"ask"},
      {"phonetic":"/əˈsum/","meaning":"to suppose something is true","word":"assume"},
      {"phonetic":"/æt/","meaning":"used to indicate place or time","word":"at"},
      {"phonetic":"/əˈtæk/","meaning":"to try to hurt or criticize","word":"attack"},
      {"phonetic":"/əˈtɛnʃən/","meaning":"notice or care given to something","word":"attention"},
      {"phonetic":"/əˈtɜrni/","meaning":"a lawyer","word":"attorney"},
      {"phonetic":"/ˈɔːdiəns/","meaning":"a group of listeners or viewers","word":"audience"},
      {"phonetic":"/ˈɔːθər/","meaning":"a writer of books or articles","word":"author"},
      {"phonetic":"/əˈθɔrɪti/","meaning":"the power to make decisions or command","word":"authority"},
      {"phonetic":"/əˈveɪləbəl/","meaning":"able to be used or obtained","word":"available"},
      {"phonetic":"/əˈvɔɪd/","meaning":"to stay away from","word":"avoid"},
      {"phonetic":"/əˈweɪ/","meaning":"at a distance from a place","word":"away"},
      {"phonetic":"/ˈbeɪbi/","meaning":"a very young child","word":"baby"},
      {"phonetic":"/bæk/","meaning":"the rear part; to return","word":"back"},
      {"phonetic":"/bæd/","meaning":"not good; harmful","word":"bad"},
      {"phonetic":"/bæɡ/","meaning":"a container made of flexible material","word":"bag"},
      {"phonetic":"/bɔːl/","meaning":"a round object used in games","word":"ball"},
      {"phonetic":"/bæŋk/","meaning":"a financial institution","word":"bank"},
      {"phonetic":"/bɑr/","meaning":"a long rod; a place selling drinks","word":"bar"},
      {"phonetic":"/beɪs/","meaning":"foundation or starting point","word":"base"},
      {"phonetic":"/biː/","meaning":"to exist; linking verb","word":"be"},
      {"phonetic":"/biːt/","meaning":"to strike; to win","word":"beat"},
      {"phonetic":"/ˈbjuːtəfəl/","meaning":"very attractive","word":"beautiful"},
      {"phonetic":"/bɪˈkɔz/","meaning":"for the reason that","word":"because"},
      {"phonetic":"/bɪˈkʌm/","meaning":"to begin to be","word":"become"},
      {"phonetic":"/bɛd/","meaning":"furniture for sleeping","word":"bed"},
      {"phonetic":"/bɪˈfɔr/","meaning":"earlier than","word":"before"},
      {"phonetic":"/bɪˈɡɪn/","meaning":"to start","word":"begin"},
      {"phonetic":"/bɪˈheɪvjər/","meaning":"the way someone acts","word":"behavior"},
      {"phonetic":"/bɪˈhaɪnd/","meaning":"at the back of","word":"behind"},
      {"phonetic":"/bɪˈliːv/","meaning":"to accept as true","word":"believe"},
      {"phonetic":"/ˈbɛnəfɪt/","meaning":"an advantage or help","word":"benefit"},
      {"phonetic":"/bɛst/","meaning":"the most good or desirable","word":"best"},
      {"phonetic":"/ˈbɛtər/","meaning":"more good; improved","word":"better"},
      {"phonetic":"/bɪˈtwin/","meaning":"in the middle of two","word":"between"},
      {"phonetic":"/bɪˈjɑnd/","meaning":"further than; outside the range of","word":"beyond"},
      {"phonetic":"/bɪɡ/","meaning":"large in size","word":"big"},
      {"phonetic":"/bɪl/","meaning":"a statement of money owed; proposed law","word":"bill"},
      {"phonetic":"/ˈbɪljən/","meaning":"one thousand million (1,000,000,000)","word":"billion"},
      {"phonetic":"/bɪt/","meaning":"a small piece","word":"bit"},
      {"phonetic":"/blæk/","meaning":"the darkest color","word":"black"},
      {"phonetic":"/blʌd/","meaning":"the red fluid in bodies","word":"blood"},
      {"phonetic":"/bluː/","meaning":"the color of the sky","word":"blue"},
      {"phonetic":"/bɔrd/","meaning":"a flat piece of material; committee","word":"board"},
      {"phonetic":"/ˈbɑdi/","meaning":"the physical structure of a person or animal","word":"body"},
      {"phonetic":"/bʊk/","meaning":"a set of written pages bound together","word":"book"},
      {"phonetic":"/bɔrn/","meaning":"brought into life at birth","word":"born"},
      {"phonetic":"/boʊθ/","meaning":"the two together","word":"both"},
      {"phonetic":"/bɑks/","meaning":"a container with sides","word":"box"},
      {"phonetic":"/bɔɪ/","meaning":"a male child","word":"boy"},
      {"phonetic":"/breɪk/","meaning":"to separate into pieces; a pause","word":"break"},
      {"phonetic":"/brɪŋ/","meaning":"to carry something to a place","word":"bring"},
      {"phonetic":"/ˈbrʌðər/","meaning":"a male sibling","word":"brother"},
      {"phonetic":"/ˈbʌdʒɪt/","meaning":"a plan for spending money","word":"budget"},
      {"phonetic":"/bɪld/","meaning":"to construct","word":"build"},
      {"phonetic":"/ˈbɪldɪŋ/","meaning":"a structure with walls and a roof","word":"building"},
      {"phonetic":"/ˈbɪznəs/","meaning":"work or trade for money","word":"business"},
      {"phonetic":"/bʌt/","meaning":"however; except","word":"but"},
      {"phonetic":"/baɪ/","meaning":"to obtain by paying money","word":"buy"},
      {"phonetic":"/baɪ/","meaning":"indicates the agent or means","word":"by"},
      {"phonetic":"/kɔl/","meaning":"to cry out; to phone","word":"call"},
      {"phonetic":"/ˈkæmərə/","meaning":"a device for taking pictures","word":"camera"},
      {"phonetic":"/kæmˈpeɪn/","meaning":"an organized series of activities to achieve a goal","word":"campaign"},
      {"phonetic":"/kæn/","meaning":"to be able to; a container","word":"can"},
      {"phonetic":"/ˈkænsər/","meaning":"a disease caused by abnormal cells","word":"cancer"},
      {"phonetic":"/ˈkændɪˌdeɪt/","meaning":"a person who applies for a job or runs for office","word":"candidate"},
      {"phonetic":"/ˈkæpɪtəl/","meaning":"a city where a government sits; money for business","word":"capital"},
      {"phonetic":"/kɑr/","meaning":"a road vehicle with wheels","word":"car"},
      {"phonetic":"/kɑrd/","meaning":"a piece of thick paper used for messages or payments","word":"card"},
      {"phonetic":"/kɛr/","meaning":"attention or protection","word":"care"},
      {"phonetic":"/kəˈrɪr/","meaning":"a person's long-term job or profession","word":"career"},
      {"phonetic":"/ˈkæri/","meaning":"to hold and move something","word":"carry"},
      {"phonetic":"/keɪs/","meaning":"an instance or container","word":"case"},
      {"phonetic":"/kætʃ/","meaning":"to capture","word":"catch"},
      {"phonetic":"/kɔz/","meaning":"a reason something happens","word":"cause"},
      {"phonetic":"/sɛl/","meaning":"a small room or biological unit","word":"cell"},
      {"phonetic":"/ˈsɛntər/","meaning":"the middle point","word":"center"},
      {"phonetic":"/ˈsɛntrəl/","meaning":"in the middle; important","word":"central"},
      {"phonetic":"/ˈsɛnʧəri/","meaning":"a period of 100 years","word":"century"},
      {"phonetic":"/ˈsɜrtən/","meaning":"sure; particular","word":"certain"},
      {"phonetic":"/ˈsɜrtənli/","meaning":"definitely; for sure","word":"certainly"},
      {"phonetic":"/ʧɛr/","meaning":"a seat for one person","word":"chair"},
      {"phonetic":"/ˈʧælɪnʤ/","meaning":"a difficult task","word":"challenge"},
      {"phonetic":"/ʧæns/","meaning":"an opportunity; possibility","word":"chance"},
      {"phonetic":"/ʧeɪndʒ/","meaning":"to make different; coins given back","word":"change"},
      {"phonetic":"/ˈkærəktər/","meaning":"a person's qualities; a symbol in writing","word":"character"},
      {"phonetic":"/ʧɑrdʒ/","meaning":"to ask for payment; to attack","word":"charge"},
      {"phonetic":"/ʧɛk/","meaning":"to examine or a written order to pay","word":"check"},
      {"phonetic":"/ʧaɪld/","meaning":"a young person","word":"child"},
      {"phonetic":"/ʧɔɪs/","meaning":"an option","word":"choice"},
      {"phonetic":"/ʧuz/","meaning":"to select","word":"choose"},
      {"phonetic":"/ʧɜrʧ/","meaning":"a building for Christian worship","word":"church"},
      {"phonetic":"/ˈsɪtəzən/","meaning":"a member of a country","word":"citizen"},
      {"phonetic":"/ˈsɪti/","meaning":"a large town","word":"city"},
      {"phonetic":"/ˈsɪvəl/","meaning":"relating to citizens or non-military matters","word":"civil"},
      {"phonetic":"/kleɪm/","meaning":"to state something is true","word":"claim"},
      {"phonetic":"/klæs/","meaning":"a group or a lesson","word":"class"},
      {"phonetic":"/klɪr/","meaning":"easy to understand; free of obstructions","word":"clear"},
      {"phonetic":"/ˈklɪrli/","meaning":"in a clear way","word":"clearly"},
      {"phonetic":"/kloʊs/","meaning":"near; to shut","word":"close"},
      {"phonetic":"/koʊʧ/","meaning":"a trainer or bus","word":"coach"},
      {"phonetic":"/koʊld/","meaning":"low in temperature","word":"cold"},
      {"phonetic":"/kəˈlɛkʃən/","meaning":"a group of objects gathered together","word":"collection"},
      {"phonetic":"/ˈkɑlɪʤ/","meaning":"an institution of higher learning","word":"college"},
      {"phonetic":"/ˈkʌlər/","meaning":"the property of making things red, blue, etc.","word":"color"},
      {"phonetic":"/kʌm/","meaning":"to move toward or arrive at a place","word":"come"},
      {"phonetic":"/kəˈmɜrʃəl/","meaning":"related to business or trade","word":"commercial"},
      {"phonetic":"/ˈkɑmən/","meaning":"usual or shared by many","word":"common"},
      {"phonetic":"/kəˈmjunəti/","meaning":"a group of people living in the same area","word":"community"},
      {"phonetic":"/ˈkʌmpəni/","meaning":"a business organization","word":"company"},
      {"phonetic":"/kəmˈpɛr/","meaning":"to examine similarities and differences","word":"compare"},
      {"phonetic":"/kəmˈpjutər/","meaning":"an electronic device for processing data","word":"computer"},
      {"phonetic":"/kənˈsɜrn/","meaning":"a matter of interest or worry","word":"concern"},
      {"phonetic":"/kənˈdɪʃən/","meaning":"the state of something","word":"condition"},
      {"phonetic":"/ˈkɑnfərəns/","meaning":"a formal meeting","word":"conference"},
      {"phonetic":"/ˈkɑŋɡrəs/","meaning":"the national legislature of the US","word":"Congress"},
      {"phonetic":"/kənˈsɪdər/","meaning":"to think about carefully","word":"consider"},
      {"phonetic":"/kənˈsumər/","meaning":"a person who buys goods or services","word":"consumer"},
      {"phonetic":"/kənˈteɪn/","meaning":"to hold inside","word":"contain"},
      {"phonetic":"/kənˈtɪnju/","meaning":"to keep going","word":"continue"},
      {"phonetic":"/kənˈtroʊl/","meaning":"to have power over","word":"control"},
      {"phonetic":"/kɔst/","meaning":"the price of something","word":"cost"},
      {"phonetic":"/kʊd/","meaning":"past tense of can; indicates possibility","word":"could"},
      {"phonetic":"/ˈkʌntri/","meaning":"a nation with its own government","word":"country"},
      {"phonetic":"/ˈkʌpəl/","meaning":"two people or things together","word":"couple"},
      {"phonetic":"/kɔrs/","meaning":"a series of lessons or direction of movement","word":"course"},
      {"phonetic":"/kɔrt/","meaning":"a place where legal cases are heard","word":"court"},
      {"phonetic":"/ˈkʌvər/","meaning":"to place over or deal with a subject","word":"cover"},
      {"phonetic":"/kriˈeɪt/","meaning":"to make something new","word":"create"},
      {"phonetic":"/kraɪm/","meaning":"an act against the law","word":"crime"},
      {"phonetic":"/ˈkʌlʧərəl/","meaning":"related to culture","word":"cultural"},
      {"phonetic":"/ˈkʌlʧər/","meaning":"beliefs and practices of a group","word":"culture"},
      {"phonetic":"/kʌp/","meaning":"a small container for drinking","word":"cup"},
      {"phonetic":"/ˈkɜrənt/","meaning":"present time or a flow of water/electricity","word":"current"},
      {"phonetic":"/ˈkʌstəmər/","meaning":"a person who buys something","word":"customer"},
      {"phonetic":"/kʌt/","meaning":"to divide with a sharp tool","word":"cut"},
      {"phonetic":"/dɑrk/","meaning":"with little or no light","word":"dark"},
      {"phonetic":"/ˈdeɪtə, ˈdætə/","meaning":"facts or information","word":"data"},
      {"phonetic":"/ˈdɔtər/","meaning":"a female child","word":"daughter"},
      {"phonetic":"/deɪ/","meaning":"a 24-hour period","word":"day"},
      {"phonetic":"/dɛd/","meaning":"no longer alive","word":"dead"},
      {"phonetic":"/dil/","meaning":"an agreement or arrangement","word":"deal"},
      {"phonetic":"/dɛθ/","meaning":"the end of life","word":"death"},
      {"phonetic":"/dɪˈbeɪt/","meaning":"a discussion of different views","word":"debate"},
      {"phonetic":"/ˈdɛkeɪd/","meaning":"a period of 10 years","word":"decade"},
      {"phonetic":"/dɪˈsaɪd/","meaning":"to make a choice","word":"decide"},
      {"phonetic":"/dɪˈsɪʒən/","meaning":"a conclusion reached","word":"decision"},
      {"phonetic":"/dip/","meaning":"far down or strong","word":"deep"},
      {"phonetic":"/dɪˈfɛns/","meaning":"protection from harm; in sports or law","word":"defense"},
      {"phonetic":"/dɪˈɡri/","meaning":"a level or an academic award","word":"degree"},
      {"phonetic":"/ˈdɛməˌkræt/","meaning":"a member of the Democratic Party in the US","word":"Democrat"},
      {"phonetic":"/ˌdɛməˈkrætɪk/","meaning":"related to democracy","word":"democratic"},
      {"phonetic":"/dɪˈskraɪb/","meaning":"to explain in words","word":"describe"},
      {"phonetic":"/dɪˈzaɪn/","meaning":"a plan or drawing","word":"design"},
      {"phonetic":"/dɪˈspaɪt/","meaning":"in spite of","word":"despite"},
      {"phonetic":"/ˈdiːteɪl/","meaning":"a small part of something","word":"detail"},
      {"phonetic":"/dɪˈtɜrmɪn/","meaning":"to decide or find out","word":"determine"},
      {"phonetic":"/dɪˈvɛləp/","meaning":"to grow or improve","word":"develop"},
      {"phonetic":"/dɪˈvɛləpmənt/","meaning":"the process of growing or improving","word":"development"},
      {"phonetic":"/daɪ/","meaning":"to stop living","word":"die"},
      {"phonetic":"/ˈdɪfərəns/","meaning":"a way in which things are not the same","word":"difference"},
      {"phonetic":"/ˈdɪfərənt/","meaning":"not the same","word":"different"},
      {"phonetic":"/ˈdɪfəkəlt/","meaning":"hard to do or understand","word":"difficult"},
      {"phonetic":"/ˈdɪnər/","meaning":"the main meal of the day","word":"dinner"},
      {"phonetic":"/dəˈrɛkʃən/","meaning":"a course along which something moves","word":"direction"},
      {"phonetic":"/dəˈrɛktər/","meaning":"a person who leads an activity or company","word":"director"},
      {"phonetic":"/dɪˈskʌvər/","meaning":"to find something for the first time","word":"discover"},
      {"phonetic":"/dɪˈskʌs/","meaning":"to talk about","word":"discuss"},
      {"phonetic":"/dɪˈskʌʃən/","meaning":"a talk about something","word":"discussion"},
      {"phonetic":"/dɪˈziz/","meaning":"illness","word":"disease"},
      {"phonetic":"/duː/","meaning":"to perform an action","word":"do"},
      {"phonetic":"/ˈdɑktər/","meaning":"a person licensed to practice medicine","word":"doctor"},
      {"phonetic":"/dɔɡ/","meaning":"a common domestic animal","word":"dog"},
      {"phonetic":"/dɔr/","meaning":"a movable barrier for entering or leaving","word":"door"},
      {"phonetic":"/daʊn/","meaning":"toward a lower place","word":"down"},
      {"phonetic":"/drɔ/","meaning":"to make a picture or pull something","word":"draw"},
      {"phonetic":"/drim/","meaning":"thoughts or images during sleep; a goal","word":"dream"},
      {"phonetic":"/draɪv/","meaning":"to operate a vehicle","word":"drive"},
      {"phonetic":"/drɑp/","meaning":"to fall or let something fall","word":"drop"},
      {"phonetic":"/drʌɡ/","meaning":"a substance used as medicine or narcotic","word":"drug"},
      {"phonetic":"/ˈdjʊrɪŋ/","meaning":"throughout a time","word":"during"},
      {"phonetic":"/iːʧ/","meaning":"every one separately","word":"each"},
      {"phonetic":"/ˈɜrli/","meaning":"before the usual time","word":"early"},
      {"phonetic":"/iːst/","meaning":"the direction opposite west","word":"east"},
      {"phonetic":"/ˈiːzi/","meaning":"not difficult","word":"easy"},
      {"phonetic":"/iːt/","meaning":"to put food into the mouth and swallow","word":"eat"},
      {"phonetic":"/ˌɛkəˈnɑmɪk/","meaning":"related to the economy","word":"economic"},
      {"phonetic":"/ɪˈkɑnəmi/","meaning":"the system of money and trade in a country","word":"economy"},
      {"phonetic":"/ɛdʒ/","meaning":"the border or part near the boundary","word":"edge"},
      {"phonetic":"/ˌɛʤəˈkeɪʃən/","meaning":"the process of learning","word":"education"},
      {"phonetic":"/ɪˈfɛkt/","meaning":"a result or influence","word":"effect"},
      {"phonetic":"/ˈɛfərt/","meaning":"physical or mental energy used","word":"effort"},
      {"phonetic":"/eɪt/","meaning":"the number 8","word":"eight"},
      {"phonetic":"/ˈiðər/","meaning":"one or the other","word":"either"},
      {"phonetic":"/ɪˈlɛkʃən/","meaning":"the act of choosing by voting","word":"election"},
      {"phonetic":"/ɛls/","meaning":"in addition; different","word":"else"},
      {"phonetic":"/ɛmˈplɔɪiː/","meaning":"a person who works for someone","word":"employee"},
      {"phonetic":"/ɛnd/","meaning":"the final part","word":"end"},
      {"phonetic":"/ˈɛnərdʒi/","meaning":"power to do work","word":"energy"},
      {"phonetic":"/ɛnˈʤɔɪ/","meaning":"to take pleasure in","word":"enjoy"},
      {"phonetic":"/ɪˈnʌf/","meaning":"as much as needed","word":"enough"},
      {"phonetic":"/ˈɛntər/","meaning":"to go inside","word":"enter"},
      {"phonetic":"/ɪnˈtaɪər/","meaning":"whole; complete","word":"entire"},
      {"phonetic":"/ɪnˈvaɪrənmənt/","meaning":"surroundings; natural world","word":"environment"},
      {"phonetic":"/ɪnˌvaɪrənˈmɛntəl/","meaning":"related to the environment","word":"environmental"},
      {"phonetic":"/əˈspɛʃəli/","meaning":"more than others; particularly","word":"especially"},
      {"phonetic":"/ɪˈstæblɪʃ/","meaning":"to set up or create","word":"establish"},
      {"phonetic":"/ˈivən/","meaning":"flat; equal; surprisingly","word":"even"},
      {"phonetic":"/ˈivnɪŋ/","meaning":"the part of day after afternoon","word":"evening"},
      {"phonetic":"/ɪˈvɛnt/","meaning":"something that happens","word":"event"},
      {"phonetic":"/ˈɛvər/","meaning":"at any time","word":"ever"},
      {"phonetic":"/ˈɛvri/","meaning":"each one in a group","word":"every"},
      {"phonetic":"/ˈɛvribɑdi/","meaning":"all people","word":"everybody"},
      {"phonetic":"/ˈɛvrɪˌwʌn/","meaning":"all people","word":"everyone"},
      {"phonetic":"/ˈɛvrɪˌθɪŋ/","meaning":"all things","word":"everything"},
      {"phonetic":"/ˈɛvədəns/","meaning":"facts or signs showing something is true","word":"evidence"},
      {"phonetic":"/ɪɡˈzæktli/","meaning":"precisely","word":"exactly"},
      {"phonetic":"/ɪɡˈzæmpəl/","meaning":"a specific case or instance","word":"example"},
      {"phonetic":"/ɪɡˈzɛkjətɪv/","meaning":"a person with top management power","word":"executive"},
      {"phonetic":"/ɪɡˈzɪst/","meaning":"to be real or alive","word":"exist"},
      {"phonetic":"/ɪkˈspɛkt/","meaning":"to think something will happen","word":"expect"},
      {"phonetic":"/ɪkˈspɪriəns/","meaning":"knowledge from doing or seeing","word":"experience"},
      {"phonetic":"/ˈɛkspɜrt/","meaning":"a person with special knowledge","word":"expert"},
      {"phonetic":"/ɪkˈspleɪn/","meaning":"to make something clear","word":"explain"},
      {"phonetic":"/aɪ/","meaning":"the organ used for seeing","word":"eye"},
      {"phonetic":"/feɪs/","meaning":"the front of the head","word":"face"},
      {"phonetic":"/fækt/","meaning":"a thing that is true","word":"fact"},
      {"phonetic":"/ˈfæktər/","meaning":"something that influences a result","word":"factor"},
      {"phonetic":"/feɪl/","meaning":"to not succeed","word":"fail"},
      {"phonetic":"/fɔl/","meaning":"to drop down; the season autumn","word":"fall"},
      {"phonetic":"/ˈfæməli/","meaning":"a group of related people","word":"family"},
      {"phonetic":"/fɑr/","meaning":"at a great distance","word":"far"},
      {"phonetic":"/fæst/","meaning":"moving quickly","word":"fast"},
      {"phonetic":"/ˈfɑðər/","meaning":"a male parent","word":"father"},
      {"phonetic":"/fɪr/","meaning":"a feeling of being afraid","word":"fear"},
      {"phonetic":"/ˈfɛdərəl/","meaning":"related to the central government","word":"federal"},
      {"phonetic":"/fil/","meaning":"to sense or have emotions","word":"feel"},
      {"phonetic":"/ˈfilɪŋ/","meaning":"an emotion","word":"feeling"},
      {"phonetic":"/fju/","meaning":"not many","word":"few"},
      {"phonetic":"/fild/","meaning":"an open land area; a subject of study","word":"field"},
      {"phonetic":"/faɪt/","meaning":"to use force against someone","word":"fight"},
      {"phonetic":"/ˈfɪɡjər/","meaning":"a number, shape, or person","word":"figure"},
      {"phonetic":"/fɪl/","meaning":"to make full","word":"fill"},
      {"phonetic":"/fɪlm/","meaning":"a movie","word":"film"},
      {"phonetic":"/ˈfaɪnəl/","meaning":"last; ultimate","word":"final"},
      {"phonetic":"/ˈfaɪnəli/","meaning":"at the end","word":"finally"},
      {"phonetic":"/fəˈnænʃəl/","meaning":"related to money","word":"financial"},
      {"phonetic":"/faɪnd/","meaning":"to discover or locate","word":"find"},
      {"phonetic":"/faɪn/","meaning":"good; thin; a penalty","word":"fine"},
      {"phonetic":"/ˈfɪŋɡər/","meaning":"one of the five parts of a hand","word":"finger"},
      {"phonetic":"/ˈfɪnɪʃ/","meaning":"to complete","word":"finish"},
      {"phonetic":"/ˈfaɪər/","meaning":"flames, or to dismiss from a job","word":"fire"},
      {"phonetic":"/fɜrm/","meaning":"a company; hard or solid","word":"firm"},
      {"phonetic":"/fɜrst/","meaning":"before all others","word":"first"},
      {"phonetic":"/fɪʃ/","meaning":"a water animal with gills","word":"fish"},
      {"phonetic":"/faɪv/","meaning":"the number 5","word":"five"},
      {"phonetic":"/flɔr/","meaning":"the surface inside a room","word":"floor"},
      {"phonetic":"/flaɪ/","meaning":"to move in the air","word":"fly"},
      {"phonetic":"/ˈfoʊkəs/","meaning":"to direct attention to","word":"focus"},
      {"phonetic":"/ˈfɑloʊ/","meaning":"to go behind or come after","word":"follow"},
      {"phonetic":"/fuːd/","meaning":"what people or animals eat","word":"food"},
      {"phonetic":"/fʊt/","meaning":"the lower part of the leg","word":"foot"},
      {"phonetic":"/fɔr/","meaning":"used to show purpose or reason","word":"for"},
      {"phonetic":"/fɔrs/","meaning":"strength or power","word":"force"},
      {"phonetic":"/ˈfɔrən/","meaning":"from another country","word":"foreign"},
      {"phonetic":"/fərˈɡɛt/","meaning":"to fail to remember","word":"forget"},
      {"phonetic":"/fɔrm/","meaning":"a shape or type; a paper document","word":"form"},
      {"phonetic":"/ˈfɔrmər/","meaning":"previous","word":"former"},
      {"phonetic":"/ˈfɔrwərd/","meaning":"toward the front","word":"forward"},
      {"phonetic":"/fɔr/","meaning":"the number 4","word":"four"},
      {"phonetic":"/fri/","meaning":"not under control; costing nothing","word":"free"},
      {"phonetic":"/frɛnd/","meaning":"a person you like and trust","word":"friend"},
      {"phonetic":"/frʌm/","meaning":"indicating origin or starting point","word":"from"},
      {"phonetic":"/frʌnt/","meaning":"the forward part","word":"front"},
      {"phonetic":"/fʊl/","meaning":"containing as much as possible","word":"full"},
      {"phonetic":"/fʌnd/","meaning":"money set aside for a purpose","word":"fund"},
      {"phonetic":"/ˈfjuʧər/","meaning":"time that has not yet come","word":"future"},
      {"phonetic":"/ɡeɪm/","meaning":"an activity with rules; a sport or play","word":"game"},
      {"phonetic":"/ˈɡɑrdən/","meaning":"a piece of land for growing plants","word":"garden"},
      {"phonetic":"/ɡæs/","meaning":"a substance like air; fuel for cars","word":"gas"},
      {"phonetic":"/ˈdʒɛnərəl/","meaning":"common; not specific; a high military rank","word":"general"},
      {"phonetic":"/ˌdʒɛnəˈreɪʃən/","meaning":"all people born around the same time","word":"generation"},
      {"phonetic":"/ɡɛt/","meaning":"to obtain, receive, or become","word":"get"},
      {"phonetic":"/ɡɜrl/","meaning":"a female child","word":"girl"},
      {"phonetic":"/ɡɪv/","meaning":"to provide something to someone","word":"give"},
      {"phonetic":"/ɡlæs/","meaning":"a container for drinking; transparent material","word":"glass"},
      {"phonetic":"/ɡoʊ/","meaning":"to move from one place to another","word":"go"},
      {"phonetic":"/ɡoʊl/","meaning":"an aim or target","word":"goal"},
      {"phonetic":"/ɡʊd/","meaning":"having positive quality","word":"good"},
      {"phonetic":"/ˈɡʌvərnmənt/","meaning":"the system by which a country is governed","word":"government"},
      {"phonetic":"/ɡreɪt/","meaning":"very good or large","word":"great"},
      {"phonetic":"/ɡrin/","meaning":"the color of grass or leaves","word":"green"},
      {"phonetic":"/ɡraʊnd/","meaning":"the solid surface of the earth","word":"ground"},
      {"phonetic":"/ɡruːp/","meaning":"a number of people or things together","word":"group"},
      {"phonetic":"/ɡroʊ/","meaning":"to increase in size or develop","word":"grow"},
      {"phonetic":"/ɡroʊθ/","meaning":"the process of growing","word":"growth"},
      {"phonetic":"/ɡɛs/","meaning":"to estimate or suppose","word":"guess"},
      {"phonetic":"/ɡʌn/","meaning":"a weapon that shoots bullets","word":"gun"},
      {"phonetic":"/ɡaɪ/","meaning":"a man","word":"guy"},
      {"phonetic":"/hɛr/","meaning":"threadlike growth on the head or body","word":"hair"},
      {"phonetic":"/hæf/","meaning":"one of two equal parts","word":"half"},
      {"phonetic":"/hænd/","meaning":"the end of the arm used for holding","word":"hand"},
      {"phonetic":"/hæŋ/","meaning":"to suspend or attach from above","word":"hang"},
      {"phonetic":"/ˈhæpən/","meaning":"to occur","word":"happen"},
      {"phonetic":"/ˈhæpi/","meaning":"feeling pleasure or joy","word":"happy"},
      {"phonetic":"/hɑrd/","meaning":"solid or difficult","word":"hard"},
      {"phonetic":"/hæv/","meaning":"to own, hold, or possess","word":"have"},
      {"phonetic":"/hi/","meaning":"a male person or animal","word":"he"},
      {"phonetic":"/hɛd/","meaning":"the upper part of the body","word":"head"},
      {"phonetic":"/hɛlθ/","meaning":"the condition of body or mind","word":"health"},
      {"phonetic":"/hɪr/","meaning":"to perceive sound","word":"hear"},
      {"phonetic":"/hɑrt/","meaning":"the organ that pumps blood; core of something","word":"heart"},
      {"phonetic":"/hit/","meaning":"high temperature","word":"heat"},
      {"phonetic":"/ˈhɛvi/","meaning":"of great weight","word":"heavy"},
      {"phonetic":"/hɛlp/","meaning":"to assist","word":"help"},
      {"phonetic":"/hɜr/","meaning":"possessive pronoun referring to a female","word":"her"},
      {"phonetic":"/hɪr/","meaning":"in this place","word":"here"},
      {"phonetic":"/hɜrˈsɛlf/","meaning":"referring to a female as object of verb","word":"herself"},
      {"phonetic":"/haɪ/","meaning":"tall or elevated","word":"high"},
      {"phonetic":"/hɪm/","meaning":"object pronoun referring to a male","word":"him"},
      {"phonetic":"/hɪmˈsɛlf/","meaning":"referring to a male as object","word":"himself"},
      {"phonetic":"/hɪz/","meaning":"possessive pronoun referring to a male","word":"his"},
      {"phonetic":"/ˈhɪstəri/","meaning":"study of past events","word":"history"},
      {"phonetic":"/hɪt/","meaning":"to strike","word":"hit"},
      {"phonetic":"/hoʊld/","meaning":"to grasp or keep","word":"hold"},
      {"phonetic":"/hoʊm/","meaning":"the place where one lives","word":"home"},
      {"phonetic":"/hoʊp/","meaning":"to desire something will happen","word":"hope"},
      {"phonetic":"/ˈhɑspɪtəl/","meaning":"place for medical care","word":"hospital"},
      {"phonetic":"/hɑt/","meaning":"having a high temperature","word":"hot"},
      {"phonetic":"/hoʊˈtɛl/","meaning":"a place where people stay when traveling","word":"hotel"},
      {"phonetic":"/aʊər/","meaning":"60 minutes; a time period","word":"hour"},
      {"phonetic":"/haʊs/","meaning":"a building for people to live in","word":"house"},
      {"phonetic":"/haʊ/","meaning":"in what way; by what means","word":"how"},
      {"phonetic":"/haʊˈɛvər/","meaning":"nevertheless; but","word":"however"},
      {"phonetic":"/hjuːdʒ/","meaning":"very large","word":"huge"},
      {"phonetic":"/ˈhjumən/","meaning":"relating to people","word":"human"},
      {"phonetic":"/ˈhʌndrəd/","meaning":"the number 100","word":"hundred"},
      {"phonetic":"/ˈhʌzbənd/","meaning":"a married man","word":"husband"},
      {"phonetic":"/aɪ/","meaning":"the person speaking or writing","word":"I"},
      {"phonetic":"/aɪˈdiə/","meaning":"a thought or plan","word":"idea"},
      {"phonetic":"/aɪˈdɛntɪˌfaɪ/","meaning":"to recognize or name","word":"identify"},
      {"phonetic":"/ɪf/","meaning":"on the condition that","word":"if"},
      {"phonetic":"/ˈɪmɪdʒ/","meaning":"a picture or representation","word":"image"},
      {"phonetic":"/ɪˈmædʒən/","meaning":"to form a picture in the mind","word":"imagine"},
      {"phonetic":"/ˈɪmpækt/","meaning":"a strong effect","word":"impact"},
      {"phonetic":"/ɪmˈpɔrtənt/","meaning":"of great significance","word":"important"},
      {"phonetic":"/ɪmˈpruv/","meaning":"to make better","word":"improve"},
      {"phonetic":"/ɪn/","meaning":"inside or within","word":"in"},
      {"phonetic":"/ɪnˈklud/","meaning":"to make part of a whole","word":"include"},
      {"phonetic":"/ɪnˈkludɪŋ/","meaning":"as part of","word":"including"},
      {"phonetic":"/ˈɪnkriːs/","meaning":"to become larger or more","word":"increase"},
      {"phonetic":"/ɪnˈdid/","meaning":"really; truly","word":"indeed"},
      {"phonetic":"/ˈɪndəˌkeɪt/","meaning":"to show or point out","word":"indicate"},
      {"phonetic":"/ˌɪndəˈvɪdʒuəl/","meaning":"a single person or thing","word":"individual"},
      {"phonetic":"/ˈɪndəstri/","meaning":"business or manufacturing","word":"industry"},
      {"phonetic":"/ˌɪnfərˈmeɪʃən/","meaning":"facts or knowledge","word":"information"},
      {"phonetic":"/ɪnˈsaɪd/","meaning":"within","word":"inside"},
      {"phonetic":"/ɪnˈstɛd/","meaning":"as a substitute","word":"instead"},
      {"phonetic":"/ˌɪnstɪˈtuʃən/","meaning":"an organization or establishment","word":"institution"},
      {"phonetic":"/ˈɪntrəst/","meaning":"curiosity or advantage","word":"interest"},
      {"phonetic":"/ˈɪntrəstɪŋ/","meaning":"holding attention","word":"interesting"},
      {"phonetic":"/ˌɪntərˈnæʃənəl/","meaning":"between nations","word":"international"},
      {"phonetic":"/ˈɪntərˌvju/","meaning":"a meeting for questions or discussion","word":"interview"},
      {"phonetic":"/ˈɪntu/","meaning":"to the inside of","word":"into"},
      {"phonetic":"/ɪnˈvɛstmənt/","meaning":"money put in for profit","word":"investment"},
      {"phonetic":"/ɪnˈvɑlv/","meaning":"to include or engage","word":"involve"},
      {"phonetic":"/ˈɪʃu/","meaning":"a topic or problem","word":"issue"},
      {"phonetic":"/ɪt/","meaning":"used to refer to a thing","word":"it"},
      {"phonetic":"/ˈaɪtəm/","meaning":"an individual thing","word":"item"},
      {"phonetic":"/ɪts/","meaning":"possessive pronoun for it","word":"its"},
      {"phonetic":"/ɪtˈsɛlf/","meaning":"referring to a thing as object","word":"itself"},
      {"phonetic":"/ʤɑb/","meaning":"work done for pay","word":"job"},
      {"phonetic":"/ʤɔɪn/","meaning":"to connect or become a member","word":"join"},
      {"phonetic":"/ʤʌst/","meaning":"exactly; fair; recently","word":"just"},
      {"phonetic":"/kip/","meaning":"to hold or maintain","word":"keep"},
      {"phonetic":"/ki/","meaning":"important; a device to open a lock","word":"key"},
      {"phonetic":"/kɪd/","meaning":"a child","word":"kid"},
      {"phonetic":"/kɪl/","meaning":"to cause death","word":"kill"},
      {"phonetic":"/kaɪnd/","meaning":"type; gentle","word":"kind"},
      {"phonetic":"/ˈkɪʧən/","meaning":"room for cooking","word":"kitchen"},
      {"phonetic":"/noʊ/","meaning":"to have knowledge","word":"know"},
      {"phonetic":"/ˈnɑlɪdʒ/","meaning":"facts, information, and skills","word":"knowledge"},
      {"phonetic":"/lænd/","meaning":"ground or territory","word":"land"},
      {"phonetic":"/ˈlæŋɡwɪdʒ/","meaning":"a system of communication","word":"language"},
      {"phonetic":"/lɑrdʒ/","meaning":"big in size","word":"large"},
      {"phonetic":"/læst/","meaning":"final; to continue","word":"last"},
      {"phonetic":"/leɪt/","meaning":"after the expected time","word":"late"},
      {"phonetic":"/ˈleɪtər/","meaning":"afterwards","word":"later"},
      {"phonetic":"/læf/","meaning":"to make a happy sound","word":"laugh"},
      {"phonetic":"/lɔ/","meaning":"rules enforced by a government","word":"law"},
      {"phonetic":"/ˈlɔjər/","meaning":"a person who practices law","word":"lawyer"},
      {"phonetic":"/leɪ/","meaning":"to put something down","word":"lay"},
      {"phonetic":"/liːd/","meaning":"to guide or be in charge","word":"lead"},
      {"phonetic":"/ˈliːdər/","meaning":"a person in charge","word":"leader"},
      {"phonetic":"/lɜrn/","meaning":"to gain knowledge","word":"learn"},
      {"phonetic":"/list/","meaning":"smallest in amount","word":"least"},
      {"phonetic":"/liv/","meaning":"to go away; to allow to remain","word":"leave"},
      {"phonetic":"/lɛft/","meaning":"opposite of right; departed","word":"left"},
      {"phonetic":"/lɛɡ/","meaning":"limb used for standing or walking","word":"leg"},
      {"phonetic":"/ˈliɡəl/","meaning":"related to law","word":"legal"},
      {"phonetic":"/lɛs/","meaning":"smaller in amount","word":"less"},
      {"phonetic":"/lɛt/","meaning":"to allow","word":"let"},
      {"phonetic":"/ˈlɛtər/","meaning":"a written message","word":"letter"},
      {"phonetic":"/ˈlɛvəl/","meaning":"height or degree","word":"level"},
      {"phonetic":"/laɪ/","meaning":"to recline; an untruth","word":"lie"},
      {"phonetic":"/laɪf/","meaning":"existence; living","word":"life"},
      {"phonetic":"/laɪt/","meaning":"visible brightness; not heavy","word":"light"},
      {"phonetic":"/laɪk/","meaning":"to enjoy or similar to","word":"like"},
      {"phonetic":"/ˈlaɪkli/","meaning":"probable","word":"likely"},
      {"phonetic":"/laɪn/","meaning":"a long narrow mark or row","word":"line"},
      {"phonetic":"/lɪst/","meaning":"a series of items","word":"list"},
      {"phonetic":"/ˈlɪsən/","meaning":"to pay attention to sound","word":"listen"},
      {"phonetic":"/ˈlɪtəl/","meaning":"small in size or amount","word":"little"},
      {"phonetic":"/lɪv/","meaning":"to be alive; to reside","word":"live"},
      {"phonetic":"/ˈloʊkəl/","meaning":"related to a nearby area","word":"local"},
      {"phonetic":"/lɔŋ/","meaning":"having great length; duration","word":"long"},
      {"phonetic":"/lʊk/","meaning":"to direct eyes toward","word":"look"},
      {"phonetic":"/luːz/","meaning":"to fail to keep or win","word":"lose"},
      {"phonetic":"/lɔs/","meaning":"the fact of losing","word":"loss"},
      {"phonetic":"/lɑt/","meaning":"many; a group; a piece of land","word":"lot"},
      {"phonetic":"/lʌv/","meaning":"a deep feeling of affection","word":"love"},
      {"phonetic":"/loʊ/","meaning":"not high; small in amount","word":"low"},
      {"phonetic":"/məˈʃin/","meaning":"a device that does work","word":"machine"},
      {"phonetic":"/ˌmæɡəˈzin/","meaning":"a publication with articles","word":"magazine"},
      {"phonetic":"/meɪn/","meaning":"most important","word":"main"},
      {"phonetic":"/meɪnˈteɪn/","meaning":"to keep in good condition","word":"maintain"},
      {"phonetic":"/ˈmeɪdʒər/","meaning":"important; a field of study","word":"major"},
      {"phonetic":"/məˈdʒɔrəti/","meaning":"more than half","word":"majority"},
      {"phonetic":"/meɪk/","meaning":"to create or cause","word":"make"},
      {"phonetic":"/mæn/","meaning":"an adult male","word":"man"},
      {"phonetic":"/ˈmænɪdʒ/","meaning":"to control or organize","word":"manage"},
      {"phonetic":"/ˈmænɪdʒmənt/","meaning":"the act of managing","word":"management"},
      {"phonetic":"/ˈmænɪdʒər/","meaning":"a person who manages","word":"manager"},
      {"phonetic":"/ˈmɛni/","meaning":"a large number","word":"many"},
      {"phonetic":"/ˈmɑrkɪt/","meaning":"a place to buy and sell; demand","word":"market"},
      {"phonetic":"/ˈmærɪdʒ/","meaning":"the state of being married","word":"marriage"},
      {"phonetic":"/məˈtɪriəl/","meaning":"substance or fabric","word":"material"},
      {"phonetic":"/ˈmætər/","meaning":"a subject or thing","word":"matter"},
      {"phonetic":"/meɪ/","meaning":"to be allowed; might","word":"may"},
      {"phonetic":"/ˈmeɪbi/","meaning":"perhaps","word":"maybe"},
      {"phonetic":"/mi/","meaning":"the speaker as object","word":"me"},
      {"phonetic":"/miːn/","meaning":"to signify; to intend","word":"mean"},
      {"phonetic":"/ˈmɛʒər/","meaning":"to find the size, amount, or degree","word":"measure"},
      {"phonetic":"/ˈmidiə/","meaning":"means of communication","word":"media"},
      {"phonetic":"/ˈmɛdɪkəl/","meaning":"related to medicine","word":"medical"},
      {"phonetic":"/mit/","meaning":"to come together","word":"meet"},
      {"phonetic":"/ˈmitɪŋ/","meaning":"an assembly of people","word":"meeting"},
      {"phonetic":"/ˈmɛmbər/","meaning":"a person belonging to a group","word":"member"},
      {"phonetic":"/ˈmɛməri/","meaning":"the ability to recall information","word":"memory"},
      {"phonetic":"/ˈmɛnʃən/","meaning":"to refer to","word":"mention"},
      {"phonetic":"/ˈmɛsɪdʒ/","meaning":"information sent to someone","word":"message"},
      {"phonetic":"/ˈmɛθəd/","meaning":"a way of doing something","word":"method"},
      {"phonetic":"/ˈmɪdəl/","meaning":"the center","word":"middle"},
      {"phonetic":"/maɪt/","meaning":"used to express possibility","word":"might"},
      {"phonetic":"/ˈmɪlɪˌtɛri/","meaning":"related to the armed forces","word":"military"},
      {"phonetic":"/ˈmɪljən/","meaning":"the number 1,000,000","word":"million"},
      {"phonetic":"/maɪnd/","meaning":"the thinking part of a person","word":"mind"},
      {"phonetic":"/ˈmɪnət/","meaning":"60 seconds; very small","word":"minute"},
      {"phonetic":"/mɪs/","meaning":"to fail to hit; to fail to attend","word":"miss"},
      {"phonetic":"/ˈmɪʃən/","meaning":"a task or purpose","word":"mission"},
      {"phonetic":"/ˈmɑdəl/","meaning":"a representation or example","word":"model"},
      {"phonetic":"/ˈmɑdərn/","meaning":"related to the present time","word":"modern"},
      {"phonetic":"/ˈmoʊmənt/","meaning":"a very short period of time","word":"moment"},
      {"phonetic":"/ˈmʌni/","meaning":"currency used for exchange","word":"money"},
      {"phonetic":"/mʌnθ/","meaning":"one of 12 parts of a year","word":"month"},
      {"phonetic":"/mɔr/","meaning":"additional; a greater amount","word":"more"},
      {"phonetic":"/ˈmɔrnɪŋ/","meaning":"early part of the day","word":"morning"},
      {"phonetic":"/moʊst/","meaning":"the majority; very","word":"most"},
      {"phonetic":"/ˈmʌðər/","meaning":"a female parent","word":"mother"},
      {"phonetic":"/maʊθ/","meaning":"the opening in the face for eating and speaking","word":"mouth"},
      {"phonetic":"/muːv/","meaning":"to change position","word":"move"},
      {"phonetic":"/ˈmuːvmənt/","meaning":"an act of moving","word":"movement"},
      {"phonetic":"/ˈmuːvi/","meaning":"a film","word":"movie"},
      {"phonetic":"/ˈmɪstər/","meaning":"title for a man","word":"Mr."},
      {"phonetic":"/ˈmɪsɪz/","meaning":"title for a married woman","word":"Mrs."},
      {"phonetic":"/mɪz/","meaning":"title for a woman","word":"Ms."},
      {"phonetic":"/mʌʧ/","meaning":"a large amount","word":"much"},
      {"phonetic":"/ˈmjuzɪk/","meaning":"organized sound for enjoyment","word":"music"},
      {"phonetic":"/mʌst/","meaning":"required; necessary","word":"must"},
      {"phonetic":"/maɪ/","meaning":"possessive pronoun","word":"my"},
      {"phonetic":"/maɪˈsɛlf/","meaning":"referring to the speaker as object","word":"myself"},
      {"phonetic":"/neɪm/","meaning":"a word by which a person or thing is known","word":"name"},
      {"phonetic":"/ˈneɪʃən/","meaning":"a country or people with shared culture","word":"nation"},
      {"phonetic":"/ˈnæʃənəl/","meaning":"relating to a nation","word":"national"},
      {"phonetic":"/ˈnætʃərəl/","meaning":"existing in nature; not made by humans","word":"natural"},
      {"phonetic":"/ˈneɪʧər/","meaning":"the physical world; inherent qualities","word":"nature"},
      {"phonetic":"/nɪr/","meaning":"close to","word":"near"},
      {"phonetic":"/ˈnɪrli/","meaning":"almost","word":"nearly"},
      {"phonetic":"/ˈnɛsəˌsɛri/","meaning":"required; essential","word":"necessary"},
      {"phonetic":"/nid/","meaning":"to require something","word":"need"},
      {"phonetic":"/ˈnɛtwɜrk/","meaning":"a group of interconnected things","word":"network"},
      {"phonetic":"/ˈproʊdus/","meaning":"to make or create; fruits and vegetables","word":"produce"},
      {"phonetic":"/ˈprɑdʌkt/","meaning":"something produced or made","word":"product"},
      {"phonetic":"/prəˈfɛʃənəl/","meaning":"related to work; a skilled person","word":"professional"},
      {"phonetic":"/prəˈfɛsər/","meaning":"a teacher at a college","word":"professor"},
      {"phonetic":"/ˈproʊɡræm/","meaning":"a plan; a set of instructions","word":"program"},
      {"phonetic":"/ˈprɑʤɛkt/","meaning":"a planned task","word":"project"},
      {"phonetic":"/ˈprɑpərti/","meaning":"something owned; a characteristic","word":"property"},
      {"phonetic":"/prəˈtɛkt/","meaning":"to keep safe from harm","word":"protect"},
      {"phonetic":"/pruv/","meaning":"to demonstrate truth by evidence","word":"prove"},
      {"phonetic":"/prəˈvaɪd/","meaning":"to supply or make available","word":"provide"},
      {"phonetic":"/ˈpʌblɪk/","meaning":"relating to people in general; open to all","word":"public"},
      {"phonetic":"/pʊl/","meaning":"to draw or haul toward oneself","word":"pull"},
      {"phonetic":"/ˈpɜrpəs/","meaning":"the reason for which something is done","word":"purpose"},
      {"phonetic":"/pʊʃ/","meaning":"to apply force to move something away","word":"push"},
      {"phonetic":"/pʊt/","meaning":"to place something in a position","word":"put"},
      {"phonetic":"/ˈkwɑləti/","meaning":"the standard or feature of something","word":"quality"},
      {"phonetic":"/ˈkwɛsʧən/","meaning":"a sentence asking for information","word":"question"},
      {"phonetic":"/wɪˈðɪn/","meaning":"inside; not beyond","word":"within"},
      {"phonetic":"/wɪˈðaʊt/","meaning":"not having; lacking","word":"without"},
      {"phonetic":"/ˈwʊmən/","meaning":"an adult female human being","word":"woman"},
      {"phonetic":"/ˈwʌndər/","meaning":"a feeling of amazement; to question","word":"wonder"},
      {"phonetic":"/wɜrd/","meaning":"a single unit of language","word":"word"},
      {"phonetic":"/wɜrk/","meaning":"activity involving effort; employment","word":"work"},
      {"phonetic":"/ˈwɜrkər/","meaning":"a person who works","word":"worker"},
      {"phonetic":"/wɜrld/","meaning":"the earth and all its people","word":"world"},
      {"phonetic":"/ˈwɜri/","meaning":"to feel anxious or troubled","word":"worry"},
      {"phonetic":"/raɪt/","meaning":"to form letters or words on a surface","word":"write"},
      {"phonetic":"/ˈraɪtər/","meaning":"a person who writes","word":"writer"},
      {"phonetic":"/rɔŋ/","meaning":"not correct; bad","word":"wrong"},
      {"phonetic":"/jɑrd/","meaning":"an area of ground near a building","word":"yard"},
      {"phonetic":"/jæ/","meaning":"informal yes","word":"yeah"},
      {"phonetic":"/jɪr/","meaning":"a period of twelve months","word":"year"},
      {"phonetic":"/jɛs/","meaning":"used to give an affirmative reply","word":"yes"},
      {"phonetic":"/jɛt/","meaning":"up until now; still","word":"yet"},
      {"phonetic":"/ju/","meaning":"the person or people addressed","word":"you"},
      {"phonetic":"/jʌŋ/","meaning":"not old; in early life","word":"young"},
      {"phonetic":"/jʊr/","meaning":"belonging to you","word":"your"},
      {"phonetic":"/jʊrˈsɛlf/","meaning":"you personally","word":"yourself"}

    ],
    secret: "",
    displayedWord: [],
    guess: "",
    correctCount: 0,
    message: "",
    messageType: "",
    currentWordObj: "",
  },

  onLoad() {
    this.pickWord();
  },

  pickWord() {
    const { words } = this.data;
    const currentWord = words[Math.floor(Math.random() * words.length)];
    this.setData({
      currentWordObj: currentWord
    });
    const secret = currentWord.word;
    // reveal 50% letters
    let displayedWord = secret.split("").map((ch, i) => ({
      char: "",
      revealed: false
    }));
    let revealCount = Math.max(1, Math.floor(secret.length * 0.5));
    let indexes = Array.from({ length: secret.length }, (_, i) => i);
    for (let i = 0; i < revealCount; i++) {
      let idx = indexes.splice(Math.floor(Math.random() * indexes.length), 1)[0];
      displayedWord[idx].char = secret[idx];
      displayedWord[idx].revealed = true;
    }
    this.setData({
      secret,
      displayedWord,
      guess: "",
      message: "New word, start guessing!",
      messageType: "",
      phonetic: "",
      meaning: ""
    });
  },

  onInput(e) {
    this.setData({ guess: e.detail.value });
  },

  allCharsInArray(str, arr) {
    // Convert to lowercase to ignore case (optional)
    const chars = [...str];
    const match = chars.every(ch => arr.includes(ch));
    return match;
  },

  getHaveGuessedWord(displayedWord, guess){
    let haveGuessedWord=[];
    for (var i=0;i<displayedWord.length;i++) {
      if(displayedWord[i].char.length > 0){
        haveGuessedWord.push(displayedWord[i].char);
      }
    }
    haveGuessedWord.push(guess);
    return haveGuessedWord;
  },

  onGuess() {
    const { guess, secret, displayedWord, correctCount, currentWordObj } = this.data;
    if (!guess) return;

    let haveGuessedWord = this.getHaveGuessedWord(displayedWord, guess);
    if (this.allCharsInArray(secret, haveGuessedWord)) {
      // success
      let updated = secret.split("").map(ch => ({
        char: ch,
        revealed: true
      }));
      this.setData({
        displayedWord: updated,
        correctCount: correctCount + 1,
        message: "🎉 congratulations! Correct! Great job!",
        messageType: "success",
        guess: "",
        phonetic: currentWordObj.phonetic,
        meaning: currentWordObj.meaning
      });
    } else {
      let rw = false;//猜测正确与否
      // reveal any matched letters
      let updated = displayedWord.map((item, i) => {
        if (guess.toLowerCase().includes(secret[i])) {
          rw = true;
          return { char: secret[i], revealed: true };
        }
        return item;
      });
      if(rw){
        this.setData({
          displayedWord: updated,
          message: "Some letters matched — keep going!",
          messageType: "success",
          guess: ""
        });
      } else {
        this.setData({
          message: "Oops! not correct! — try again!",
          messageType: "fail",
          guess: ""
        });
      }
    }
  },

  onHint() {
    const { secret, displayedWord, currentWordObj } = this.data;
    let hiddenIndexes = displayedWord
      .map((item, i) => (!item.revealed ? i : null))
      .filter(i => i !== null);
    if (hiddenIndexes.length === 0) {
      this.setData({
         message: "No more hints!", 
         messageType: ""
        });
      return;
    }
    let idx =
      hiddenIndexes[Math.floor(Math.random() * hiddenIndexes.length)];
    displayedWord[idx] = {
      char: secret[idx],
      revealed: true
    };

    let haveGuessedWord = this.getHaveGuessedWord(displayedWord, secret[idx]);
    if(this.allCharsInArray(secret, haveGuessedWord)) {
      this.setData({
        displayedWord,
        message: "All letters have been revealed!",
        messageType: "",
        phonetic: currentWordObj.phonetic,
        meaning: currentWordObj.meaning
      });
    } else {
      this.setData({
        displayedWord,
        message: "A letter has been revealed!",
        messageType: ""
      });
    }
    this.setData({
      displayedWord,
      message: "A letter has been revealed!",
      messageType: ""
    });
  },

  onNext() {
    this.pickWord();
  },

  // 键盘按键点击事件
  onKeyTap: function(e) {
    const key = e.currentTarget.dataset.key;
    this.setData({
      guess: key
    });
    // this.setData({
    //   inputValue: this.data.inputValue + key
    // });

  },
  // 退格键点击事件
  onBackspace: function() {
    if (this.data.guess.length > 0) {
      this.setData({
        guess: this.data.guess.slice(0, -1)
      });
    }
  },
  onShareAppMessage() {
    return {
      title: '猜单词-实用小工具',
      path: '/pages/learn/guess_word/guess_word',  // 转发后打开的路径
      imageUrl: '/image/logo.png'       // 可选，自定义分享图
    }
  },
  onShareTimeline() {
    return {
      title: '猜单词-实用小工具',
      //query: 'id=123',   // 分享后带的参数
      imageUrl: '/image/logo.png'
    }
  }
});
